[package]
name = "rust-spider"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "spider",
    "spider_worker",
    "spider_cli",
    "spider_utils",
    # internal
    "examples",
    "benches"]
resolver = "2"
